import {useEffect,useState} from 'react';
import {Megaphone,MapPin,Radio,ShieldAlert,Users,Send,RefreshCw} from 'lucide-react';
import {createEmergencyBroadcast,getEmergencyOverview,sendEmergencyBroadcast} from '../../../services/emergencyService';
import './EmergencyCenter.css';
export default function EmergencyCenter(){
 const [data,setData]=useState({zones:[],shelters:[],broadcasts:[]}); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false);
 const [form,setForm]=useState({severity:'WARNING',title:'',message:'',channel:['IN_APP'],zoneId:''});
 const load=()=>getEmergencyOverview().then(r=>setData(r.data)).catch(()=>{}).finally(()=>setLoading(false));
 useEffect(()=>{load()},[]);
 async function create(e){e.preventDefault();if(!form.title||!form.message)return;setSending(true);try{const r=await createEmergencyBroadcast({...form,zoneId:form.zoneId||null});await sendEmergencyBroadcast(r.data.id);setForm({...form,title:'',message:'',zoneId:''});await load()}finally{setSending(false)}}
 const toggle=c=>setForm(f=>({...f,channel:f.channel.includes(c)?f.channel.filter(x=>x!==c):[...f.channel,c]}));
 return <div className="page emergency-center"><div className="page-head"><div><span className="eyebrow">PUBLIC SAFETY</span><h1>Emergency Communications</h1><p>Targeted evacuation warnings, shelter capacity and citizen safety messaging.</p></div><div className="live-chip"><Radio size={15}/> OPERATIONAL</div></div>
  <div className="emergency-stats"><div><ShieldAlert/><span>Evacuation Zones</span><strong>{data.zones.filter(z=>z.level==='EVACUATE').length}</strong></div><div><Users/><span>Open Shelters</span><strong>{data.shelters.filter(s=>s.status==='OPEN').length}</strong></div><div><Megaphone/><span>Broadcasts</span><strong>{data.broadcasts.length}</strong></div><div><MapPin/><span>Warning Areas</span><strong>{data.zones.filter(z=>z.level==='WARNING').length}</strong></div></div>
  <div className="emergency-grid"><section className="card broadcast-card"><div className="card-head"><div><h2>Issue Emergency Broadcast</h2><small>Phase 14 uses real backend broadcast records; external SMS/email gateways remain adapter-ready.</small></div></div><form onSubmit={create}><div className="field-row"><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{['INFO','WARNING','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select></label><label>Target Zone<select value={form.zoneId} onChange={e=>setForm({...form,zoneId:e.target.value})}><option value="">All active areas</option>{data.zones.map(z=><option value={z.id} key={z.id}>{z.name} · {z.level}</option>)}</select></label></div><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Example: Evacuate Zone 4"/></label><label>Message<textarea rows="4" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Give citizens clear, actionable instructions."/></label><div className="channel-row"><span>Channels</span>{['IN_APP','WEB','SMS','EMAIL','SIREN'].map(c=><button type="button" key={c} className={form.channel.includes(c)?'selected':''} onClick={()=>toggle(c)}>{c}</button>)}</div><button className="send-btn" disabled={sending}><Send size={16}/>{sending?'Sending…':'Create & Send Broadcast'}</button></form></section>
   <section className="card shelters-card"><div className="card-head"><div><h2>Emergency Shelters</h2><small>Capacity and operational status</small></div><button className="icon-btn" onClick={load}><RefreshCw size={16}/></button></div><div className="shelter-list">{data.shelters.map(s=><div className="shelter" key={s.id}><div><strong>{s.name}</strong><span>{s.shelter_code} · {s.status}</span></div><div className="capacity"><b>{s.capacity-s.occupied}</b><span>spaces</span><div><i style={{width:`${Math.min(100,s.occupancy_pct)}%`}}/></div></div></div>)}</div></section>
  </div>
  <section className="card zone-card"><div className="card-head"><div><h2>Active Safety Zones</h2><small>{loading?'Loading GIS safety zones…':'Use these zones to target public warnings and evacuation instructions.'}</small></div></div><div className="zone-grid">{data.zones.map(z=><div className={`zone ${z.level.toLowerCase()}`} key={z.id}><div><span>{z.level}</span><strong>{z.name}</strong></div><small>{z.shelter_name?`Nearest shelter: ${z.shelter_name}`:'No shelter assigned'}</small></div>)}</div></section>
  <section className="card broadcast-history"><div className="card-head"><div><h2>Broadcast History</h2><small>Recent citizen safety messages</small></div></div>{data.broadcasts.map(b=><div className="broadcast-row" key={b.id}><span className={`pill ${b.severity.toLowerCase()}`}>{b.severity}</span><div><strong>{b.title}</strong><p>{b.message}</p></div><span className="broadcast-status">{b.status}{b.zone_name?` · ${b.zone_name}`:''}</span></div>)}</section>
 </div>
}
